/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.pojos;


import org.jooq.types.YearToSecond;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commands implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String        command;
    private final YearToSecond  processingTime;
    private final LocalDateTime time;

    public Commands(Commands value) {
        this.command = value.command;
        this.processingTime = value.processingTime;
        this.time = value.time;
    }

    public Commands(
        String        command,
        YearToSecond  processingTime,
        LocalDateTime time
    ) {
        this.command = command;
        this.processingTime = processingTime;
        this.time = time;
    }

    /**
     * Getter for <code>public.commands.command</code>.
     */
    public String getCommand() {
        return this.command;
    }

    /**
     * Getter for <code>public.commands.processing_time</code>.
     */
    public YearToSecond getProcessingTime() {
        return this.processingTime;
    }

    /**
     * Getter for <code>public.commands.time</code>.
     */
    public LocalDateTime getTime() {
        return this.time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Commands (");

        sb.append(command);
        sb.append(", ").append(processingTime);
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }
}
