/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guilds implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String  guildId;
    private final String  commandPrefix;
    private final String  requestChannelId;
    private final Boolean requestsEnabled;
    private final String  announcementChannelId;
    private final String  joinMessages;
    private final Boolean joinMessagesEnabled;
    private final String  leaveMessages;
    private final Boolean leaveMessagesEnabled;
    private final String  boostMessages;
    private final Boolean boostMessagesEnabled;
    private final String  logChannelId;
    private final Boolean logMessagesEnabled;
    private final Boolean nsfwEnabled;
    private final String  inactiveRoleId;

    public Guilds(Guilds value) {
        this.guildId = value.guildId;
        this.commandPrefix = value.commandPrefix;
        this.requestChannelId = value.requestChannelId;
        this.requestsEnabled = value.requestsEnabled;
        this.announcementChannelId = value.announcementChannelId;
        this.joinMessages = value.joinMessages;
        this.joinMessagesEnabled = value.joinMessagesEnabled;
        this.leaveMessages = value.leaveMessages;
        this.leaveMessagesEnabled = value.leaveMessagesEnabled;
        this.boostMessages = value.boostMessages;
        this.boostMessagesEnabled = value.boostMessagesEnabled;
        this.logChannelId = value.logChannelId;
        this.logMessagesEnabled = value.logMessagesEnabled;
        this.nsfwEnabled = value.nsfwEnabled;
        this.inactiveRoleId = value.inactiveRoleId;
    }

    public Guilds(
        String  guildId,
        String  commandPrefix,
        String  requestChannelId,
        Boolean requestsEnabled,
        String  announcementChannelId,
        String  joinMessages,
        Boolean joinMessagesEnabled,
        String  leaveMessages,
        Boolean leaveMessagesEnabled,
        String  boostMessages,
        Boolean boostMessagesEnabled,
        String  logChannelId,
        Boolean logMessagesEnabled,
        Boolean nsfwEnabled,
        String  inactiveRoleId
    ) {
        this.guildId = guildId;
        this.commandPrefix = commandPrefix;
        this.requestChannelId = requestChannelId;
        this.requestsEnabled = requestsEnabled;
        this.announcementChannelId = announcementChannelId;
        this.joinMessages = joinMessages;
        this.joinMessagesEnabled = joinMessagesEnabled;
        this.leaveMessages = leaveMessages;
        this.leaveMessagesEnabled = leaveMessagesEnabled;
        this.boostMessages = boostMessages;
        this.boostMessagesEnabled = boostMessagesEnabled;
        this.logChannelId = logChannelId;
        this.logMessagesEnabled = logMessagesEnabled;
        this.nsfwEnabled = nsfwEnabled;
        this.inactiveRoleId = inactiveRoleId;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.guilds.command_prefix</code>.
     */
    public String getCommandPrefix() {
        return this.commandPrefix;
    }

    /**
     * Getter for <code>public.guilds.request_channel_id</code>.
     */
    public String getRequestChannelId() {
        return this.requestChannelId;
    }

    /**
     * Getter for <code>public.guilds.requests_enabled</code>.
     */
    public Boolean getRequestsEnabled() {
        return this.requestsEnabled;
    }

    /**
     * Getter for <code>public.guilds.announcement_channel_id</code>.
     */
    public String getAnnouncementChannelId() {
        return this.announcementChannelId;
    }

    /**
     * Getter for <code>public.guilds.join_messages</code>.
     */
    public String getJoinMessages() {
        return this.joinMessages;
    }

    /**
     * Getter for <code>public.guilds.join_messages_enabled</code>.
     */
    public Boolean getJoinMessagesEnabled() {
        return this.joinMessagesEnabled;
    }

    /**
     * Getter for <code>public.guilds.leave_messages</code>.
     */
    public String getLeaveMessages() {
        return this.leaveMessages;
    }

    /**
     * Getter for <code>public.guilds.leave_messages_enabled</code>.
     */
    public Boolean getLeaveMessagesEnabled() {
        return this.leaveMessagesEnabled;
    }

    /**
     * Getter for <code>public.guilds.boost_messages</code>.
     */
    public String getBoostMessages() {
        return this.boostMessages;
    }

    /**
     * Getter for <code>public.guilds.boost_messages_enabled</code>.
     */
    public Boolean getBoostMessagesEnabled() {
        return this.boostMessagesEnabled;
    }

    /**
     * Getter for <code>public.guilds.log_channel_id</code>.
     */
    public String getLogChannelId() {
        return this.logChannelId;
    }

    /**
     * Getter for <code>public.guilds.log_messages_enabled</code>.
     */
    public Boolean getLogMessagesEnabled() {
        return this.logMessagesEnabled;
    }

    /**
     * Getter for <code>public.guilds.nsfw_enabled</code>.
     */
    public Boolean getNsfwEnabled() {
        return this.nsfwEnabled;
    }

    /**
     * Getter for <code>public.guilds.inactive_role_id</code>.
     */
    public String getInactiveRoleId() {
        return this.inactiveRoleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Guilds (");

        sb.append(guildId);
        sb.append(", ").append(commandPrefix);
        sb.append(", ").append(requestChannelId);
        sb.append(", ").append(requestsEnabled);
        sb.append(", ").append(announcementChannelId);
        sb.append(", ").append(joinMessages);
        sb.append(", ").append(joinMessagesEnabled);
        sb.append(", ").append(leaveMessages);
        sb.append(", ").append(leaveMessagesEnabled);
        sb.append(", ").append(boostMessages);
        sb.append(", ").append(boostMessagesEnabled);
        sb.append(", ").append(logChannelId);
        sb.append(", ").append(logMessagesEnabled);
        sb.append(", ").append(nsfwEnabled);
        sb.append(", ").append(inactiveRoleId);

        sb.append(")");
        return sb.toString();
    }
}
