/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReactiveMessages implements Serializable{

	private static final long serialVersionUID = -206711688;

	private final String channelId;
	private final String messageId;
	private final String userId;
	private final String guildId;
	private final String commandId;
	private final String command;
	private final String allowed;

	public ReactiveMessages(ReactiveMessages value){
		this.channelId = value.channelId;
		this.messageId = value.messageId;
		this.userId = value.userId;
		this.guildId = value.guildId;
		this.commandId = value.commandId;
		this.command = value.command;
		this.allowed = value.allowed;
	}

	public ReactiveMessages(
			String channelId,
			String messageId,
			String userId,
			String guildId,
			String commandId,
			String command,
			String allowed
	){
		this.channelId = channelId;
		this.messageId = messageId;
		this.userId = userId;
		this.guildId = guildId;
		this.commandId = commandId;
		this.command = command;
		this.allowed = allowed;
	}

	public String getChannelId(){
		return this.channelId;
	}

	public String getMessageId(){
		return this.messageId;
	}

	public String getUserId(){
		return this.userId;
	}

	public String getGuildId(){
		return this.guildId;
	}

	public String getCommandId(){
		return this.commandId;
	}

	public String getCommand(){
		return this.command;
	}

	public String getAllowed(){
		return this.allowed;
	}

	@Override
	public String toString(){
		StringBuilder sb = new StringBuilder("ReactiveMessages (");

		sb.append(channelId);
		sb.append(", ").append(messageId);
		sb.append(", ").append(userId);
		sb.append(", ").append(guildId);
		sb.append(", ").append(commandId);
		sb.append(", ").append(command);
		sb.append(", ").append(allowed);

		sb.append(")");
		return sb.toString();
	}

}
