/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelfAssignableRoles implements Serializable {

    private static final long serialVersionUID = 964432359;

    private final String roleId;
    private final String groupId;
    private final String guildId;
    private final String emoteId;

    public SelfAssignableRoles(SelfAssignableRoles value) {
        this.roleId = value.roleId;
        this.groupId = value.groupId;
        this.guildId = value.guildId;
        this.emoteId = value.emoteId;
    }

    public SelfAssignableRoles(
        String roleId,
        String groupId,
        String guildId,
        String emoteId
    ) {
        this.roleId = roleId;
        this.groupId = groupId;
        this.guildId = guildId;
        this.emoteId = emoteId;
    }

    public String getRoleId() {
        return this.roleId;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public String getGuildId() {
        return this.guildId;
    }

    public String getEmoteId() {
        return this.emoteId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SelfAssignableRoles (");

        sb.append(roleId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(emoteId);

        sb.append(")");
        return sb.toString();
    }
}
