/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sessions implements Serializable {

    private static final long serialVersionUID = 319920994;

    private final String        sessionId;
    private final String        userId;
    private final String        accessToken;
    private final String        refreshToken;
    private final LocalDateTime expiration;

    public Sessions(Sessions value) {
        this.sessionId = value.sessionId;
        this.userId = value.userId;
        this.accessToken = value.accessToken;
        this.refreshToken = value.refreshToken;
        this.expiration = value.expiration;
    }

    public Sessions(
        String        sessionId,
        String        userId,
        String        accessToken,
        String        refreshToken,
        LocalDateTime expiration
    ) {
        this.sessionId = sessionId;
        this.userId = userId;
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
        this.expiration = expiration;
    }

    public String getSessionId() {
        return this.sessionId;
    }

    public String getUserId() {
        return this.userId;
    }

    public String getAccessToken() {
        return this.accessToken;
    }

    public String getRefreshToken() {
        return this.refreshToken;
    }

    public LocalDateTime getExpiration() {
        return this.expiration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sessions (");

        sb.append(sessionId);
        sb.append(", ").append(userId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(refreshToken);
        sb.append(", ").append(expiration);

        sb.append(")");
        return sb.toString();
    }
}
