/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStatistics implements Serializable {

    private static final long serialVersionUID = 1219551348;

    private final String  userId;
    private final String  guildId;
    private final Integer xp;
    private final Integer level;
    private final Integer botCalls;
    private final Integer voiceTime;
    private final Integer messageCount;
    private final Integer emoteCount;
    private final String  lastActive;

    public UserStatistics(UserStatistics value) {
        this.userId = value.userId;
        this.guildId = value.guildId;
        this.xp = value.xp;
        this.level = value.level;
        this.botCalls = value.botCalls;
        this.voiceTime = value.voiceTime;
        this.messageCount = value.messageCount;
        this.emoteCount = value.emoteCount;
        this.lastActive = value.lastActive;
    }

    public UserStatistics(
        String  userId,
        String  guildId,
        Integer xp,
        Integer level,
        Integer botCalls,
        Integer voiceTime,
        Integer messageCount,
        Integer emoteCount,
        String  lastActive
    ) {
        this.userId = userId;
        this.guildId = guildId;
        this.xp = xp;
        this.level = level;
        this.botCalls = botCalls;
        this.voiceTime = voiceTime;
        this.messageCount = messageCount;
        this.emoteCount = emoteCount;
        this.lastActive = lastActive;
    }

    public String getUserId() {
        return this.userId;
    }

    public String getGuildId() {
        return this.guildId;
    }

    public Integer getXp() {
        return this.xp;
    }

    public Integer getLevel() {
        return this.level;
    }

    public Integer getBotCalls() {
        return this.botCalls;
    }

    public Integer getVoiceTime() {
        return this.voiceTime;
    }

    public Integer getMessageCount() {
        return this.messageCount;
    }

    public Integer getEmoteCount() {
        return this.emoteCount;
    }

    public String getLastActive() {
        return this.lastActive;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserStatistics (");

        sb.append(userId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(xp);
        sb.append(", ").append(level);
        sb.append(", ").append(botCalls);
        sb.append(", ").append(voiceTime);
        sb.append(", ").append(messageCount);
        sb.append(", ").append(emoteCount);
        sb.append(", ").append(lastActive);

        sb.append(")");
        return sb.toString();
    }
}
