/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables;


import de.kittybot.kittybot.jooq.Keys;
import de.kittybot.kittybot.jooq.Public;
import de.kittybot.kittybot.jooq.tables.records.GuildPrefixesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildPrefixes extends TableImpl<GuildPrefixesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.guild_prefixes</code>
     */
    public static final GuildPrefixes GUILD_PREFIXES = new GuildPrefixes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuildPrefixesRecord> getRecordType() {
        return GuildPrefixesRecord.class;
    }

    /**
     * The column <code>public.guild_prefixes.guild_prefix_id</code>.
     */
    public final TableField<GuildPrefixesRecord, Long> GUILD_PREFIX_ID = createField(DSL.name("guild_prefix_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.guild_prefixes.guild_id</code>.
     */
    public final TableField<GuildPrefixesRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_prefixes.prefix</code>.
     */
    public final TableField<GuildPrefixesRecord, String> PREFIX = createField(DSL.name("prefix"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    private GuildPrefixes(Name alias, Table<GuildPrefixesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuildPrefixes(Name alias, Table<GuildPrefixesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.guild_prefixes</code> table reference
     */
    public GuildPrefixes(String alias) {
        this(DSL.name(alias), GUILD_PREFIXES);
    }

    /**
     * Create an aliased <code>public.guild_prefixes</code> table reference
     */
    public GuildPrefixes(Name alias) {
        this(alias, GUILD_PREFIXES);
    }

    /**
     * Create a <code>public.guild_prefixes</code> table reference
     */
    public GuildPrefixes() {
        this(DSL.name("guild_prefixes"), null);
    }

    public <O extends Record> GuildPrefixes(Table<O> child, ForeignKey<O, GuildPrefixesRecord> key) {
        super(child, key, GUILD_PREFIXES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<GuildPrefixesRecord, Long> getIdentity() {
        return (Identity<GuildPrefixesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GuildPrefixesRecord> getPrimaryKey() {
        return Keys.GUILD_PREFIXES_PKEY;
    }

    @Override
    public List<UniqueKey<GuildPrefixesRecord>> getKeys() {
        return Arrays.<UniqueKey<GuildPrefixesRecord>>asList(Keys.GUILD_PREFIXES_PKEY, Keys.GUILD_PREFIXES_GUILD_ID_KEY, Keys.GUILD_PREFIXES_PREFIX_KEY);
    }

    @Override
    public List<ForeignKey<GuildPrefixesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GuildPrefixesRecord, ?>>asList(Keys.GUILD_PREFIXES__GUILD_PREFIXES_GUILD_ID_FKEY);
    }

    public Guilds guilds() {
        return new Guilds(this, Keys.GUILD_PREFIXES__GUILD_PREFIXES_GUILD_ID_FKEY);
    }

    @Override
    public GuildPrefixes as(String alias) {
        return new GuildPrefixes(DSL.name(alias), this);
    }

    @Override
    public GuildPrefixes as(Name alias) {
        return new GuildPrefixes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildPrefixes rename(String name) {
        return new GuildPrefixes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildPrefixes rename(Name name) {
        return new GuildPrefixes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
