/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables;


import de.kittybot.kittybot.jooq.Keys;
import de.kittybot.kittybot.jooq.Public;
import de.kittybot.kittybot.jooq.tables.records.SelfAssignableRoleGroupsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelfAssignableRoleGroups extends TableImpl<SelfAssignableRoleGroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.self_assignable_role_groups</code>
     */
    public static final SelfAssignableRoleGroups SELF_ASSIGNABLE_ROLE_GROUPS = new SelfAssignableRoleGroups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelfAssignableRoleGroupsRecord> getRecordType() {
        return SelfAssignableRoleGroupsRecord.class;
    }

    /**
     * The column <code>public.self_assignable_role_groups.id</code>.
     */
    public final TableField<SelfAssignableRoleGroupsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.self_assignable_role_groups.guild_id</code>.
     */
    public final TableField<SelfAssignableRoleGroupsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.self_assignable_role_groups.group_name</code>.
     */
    public final TableField<SelfAssignableRoleGroupsRecord, String> GROUP_NAME = createField(DSL.name("group_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.self_assignable_role_groups.max_roles</code>.
     */
    public final TableField<SelfAssignableRoleGroupsRecord, Integer> MAX_ROLES = createField(DSL.name("max_roles"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'-1'::integer", SQLDataType.INTEGER)), this, "");

    private SelfAssignableRoleGroups(Name alias, Table<SelfAssignableRoleGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelfAssignableRoleGroups(Name alias, Table<SelfAssignableRoleGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.self_assignable_role_groups</code> table reference
     */
    public SelfAssignableRoleGroups(String alias) {
        this(DSL.name(alias), SELF_ASSIGNABLE_ROLE_GROUPS);
    }

    /**
     * Create an aliased <code>public.self_assignable_role_groups</code> table reference
     */
    public SelfAssignableRoleGroups(Name alias) {
        this(alias, SELF_ASSIGNABLE_ROLE_GROUPS);
    }

    /**
     * Create a <code>public.self_assignable_role_groups</code> table reference
     */
    public SelfAssignableRoleGroups() {
        this(DSL.name("self_assignable_role_groups"), null);
    }

    public <O extends Record> SelfAssignableRoleGroups(Table<O> child, ForeignKey<O, SelfAssignableRoleGroupsRecord> key) {
        super(child, key, SELF_ASSIGNABLE_ROLE_GROUPS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<SelfAssignableRoleGroupsRecord, Long> getIdentity() {
        return (Identity<SelfAssignableRoleGroupsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SelfAssignableRoleGroupsRecord> getPrimaryKey() {
        return Keys.SELF_ASSIGNABLE_ROLE_GROUPS_PKEY;
    }

    @Override
    public List<UniqueKey<SelfAssignableRoleGroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<SelfAssignableRoleGroupsRecord>>asList(Keys.SELF_ASSIGNABLE_ROLE_GROUPS_PKEY);
    }

    @Override
    public List<ForeignKey<SelfAssignableRoleGroupsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SelfAssignableRoleGroupsRecord, ?>>asList(Keys.SELF_ASSIGNABLE_ROLE_GROUPS__SELF_ASSIGNABLE_ROLE_GROUPS_GUILD_ID_FKEY);
    }

    public Guilds guilds() {
        return new Guilds(this, Keys.SELF_ASSIGNABLE_ROLE_GROUPS__SELF_ASSIGNABLE_ROLE_GROUPS_GUILD_ID_FKEY);
    }

    @Override
    public SelfAssignableRoleGroups as(String alias) {
        return new SelfAssignableRoleGroups(DSL.name(alias), this);
    }

    @Override
    public SelfAssignableRoleGroups as(Name alias) {
        return new SelfAssignableRoleGroups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SelfAssignableRoleGroups rename(String name) {
        return new SelfAssignableRoleGroups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SelfAssignableRoleGroups rename(Name name) {
        return new SelfAssignableRoleGroups(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
