/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.BotIgnoredMembers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotIgnoredMembersRecord extends UpdatableRecordImpl<BotIgnoredMembersRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bot_ignored_members.id</code>.
     */
    public BotIgnoredMembersRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bot_ignored_members.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bot_ignored_members.member_id</code>.
     */
    public BotIgnoredMembersRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bot_ignored_members.member_id</code>.
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BotIgnoredMembers.BOT_IGNORED_MEMBERS.ID;
    }

    @Override
    public Field<Long> field2() {
        return BotIgnoredMembers.BOT_IGNORED_MEMBERS.MEMBER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMemberId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMemberId();
    }

    @Override
    public BotIgnoredMembersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BotIgnoredMembersRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    @Override
    public BotIgnoredMembersRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BotIgnoredMembersRecord
     */
    public BotIgnoredMembersRecord() {
        super(BotIgnoredMembers.BOT_IGNORED_MEMBERS);
    }

    /**
     * Create a detached, initialised BotIgnoredMembersRecord
     */
    public BotIgnoredMembersRecord(Long id, Long memberId) {
        super(BotIgnoredMembers.BOT_IGNORED_MEMBERS);

        setId(id);
        setMemberId(memberId);
    }
}
