/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.GuildTags;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildTagsRecord extends UpdatableRecordImpl<GuildTagsRecord> implements Record6<Long, String, Long, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_tags.tag_id</code>.
     */
    public GuildTagsRecord setTagId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tags.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_tags.name</code>.
     */
    public GuildTagsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tags.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.guild_tags.guild_id</code>.
     */
    public GuildTagsRecord setGuildId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tags.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_tags.user_id</code>.
     */
    public GuildTagsRecord setUserId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tags.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guild_tags.content</code>.
     */
    public GuildTagsRecord setContent(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tags.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.guild_tags.created_at</code>.
     */
    public GuildTagsRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tags.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Long, Long, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildTags.GUILD_TAGS.TAG_ID;
    }

    @Override
    public Field<String> field2() {
        return GuildTags.GUILD_TAGS.NAME;
    }

    @Override
    public Field<Long> field3() {
        return GuildTags.GUILD_TAGS.GUILD_ID;
    }

    @Override
    public Field<Long> field4() {
        return GuildTags.GUILD_TAGS.USER_ID;
    }

    @Override
    public Field<String> field5() {
        return GuildTags.GUILD_TAGS.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return GuildTags.GUILD_TAGS.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getTagId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getGuildId();
    }

    @Override
    public Long component4() {
        return getUserId();
    }

    @Override
    public String component5() {
        return getContent();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getTagId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getGuildId();
    }

    @Override
    public Long value4() {
        return getUserId();
    }

    @Override
    public String value5() {
        return getContent();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public GuildTagsRecord value1(Long value) {
        setTagId(value);
        return this;
    }

    @Override
    public GuildTagsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GuildTagsRecord value3(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildTagsRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public GuildTagsRecord value5(String value) {
        setContent(value);
        return this;
    }

    @Override
    public GuildTagsRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GuildTagsRecord values(Long value1, String value2, Long value3, Long value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildTagsRecord
     */
    public GuildTagsRecord() {
        super(GuildTags.GUILD_TAGS);
    }

    /**
     * Create a detached, initialised GuildTagsRecord
     */
    public GuildTagsRecord(Long tagId, String name, Long guildId, Long userId, String content, LocalDateTime createdAt) {
        super(GuildTags.GUILD_TAGS);

        setTagId(tagId);
        setName(name);
        setGuildId(guildId);
        setUserId(userId);
        setContent(content);
        setCreatedAt(createdAt);
    }
}
