/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.Guilds;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.YearToSecond;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record16<Long, String, Long, Long, Boolean, String, Boolean, String, Boolean, Long, Boolean, Boolean, Long, YearToSecond, Long, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guilds.command_prefix</code>.
     */
    public GuildsRecord setCommandPrefix(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.command_prefix</code>.
     */
    public String getCommandPrefix() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.guilds.announcement_channel_id</code>.
     */
    public GuildsRecord setAnnouncementChannelId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.announcement_channel_id</code>.
     */
    public Long getAnnouncementChannelId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guilds.request_channel_id</code>.
     */
    public GuildsRecord setRequestChannelId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.request_channel_id</code>.
     */
    public Long getRequestChannelId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guilds.requests_enabled</code>.
     */
    public GuildsRecord setRequestsEnabled(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.requests_enabled</code>.
     */
    public Boolean getRequestsEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.guilds.join_message</code>.
     */
    public GuildsRecord setJoinMessage(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.join_message</code>.
     */
    public String getJoinMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.guilds.join_messages_enabled</code>.
     */
    public GuildsRecord setJoinMessagesEnabled(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.join_messages_enabled</code>.
     */
    public Boolean getJoinMessagesEnabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.guilds.leave_message</code>.
     */
    public GuildsRecord setLeaveMessage(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.leave_message</code>.
     */
    public String getLeaveMessage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.guilds.leave_messages_enabled</code>.
     */
    public GuildsRecord setLeaveMessagesEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.leave_messages_enabled</code>.
     */
    public Boolean getLeaveMessagesEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.guilds.log_channel_id</code>.
     */
    public GuildsRecord setLogChannelId(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.log_channel_id</code>.
     */
    public Long getLogChannelId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.guilds.log_messages_enabled</code>.
     */
    public GuildsRecord setLogMessagesEnabled(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.log_messages_enabled</code>.
     */
    public Boolean getLogMessagesEnabled() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.guilds.nsfw_enabled</code>.
     */
    public GuildsRecord setNsfwEnabled(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.nsfw_enabled</code>.
     */
    public Boolean getNsfwEnabled() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.guilds.inactive_role_id</code>.
     */
    public GuildsRecord setInactiveRoleId(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.inactive_role_id</code>.
     */
    public Long getInactiveRoleId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.guilds.inactive_duration</code>.
     */
    public GuildsRecord setInactiveDuration(YearToSecond value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.inactive_duration</code>.
     */
    public YearToSecond getInactiveDuration() {
        return (YearToSecond) get(13);
    }

    /**
     * Setter for <code>public.guilds.dj_role_id</code>.
     */
    public GuildsRecord setDjRoleId(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.dj_role_id</code>.
     */
    public Long getDjRoleId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>public.guilds.snipes_enabled</code>.
     */
    public GuildsRecord setSnipesEnabled(Boolean value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.snipes_enabled</code>.
     */
    public Boolean getSnipesEnabled() {
        return (Boolean) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, Long, Long, Boolean, String, Boolean, String, Boolean, Long, Boolean, Boolean, Long, YearToSecond, Long, Boolean> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, String, Long, Long, Boolean, String, Boolean, String, Boolean, Long, Boolean, Boolean, Long, YearToSecond, Long, Boolean> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<String> field2() {
        return Guilds.GUILDS.COMMAND_PREFIX;
    }

    @Override
    public Field<Long> field3() {
        return Guilds.GUILDS.ANNOUNCEMENT_CHANNEL_ID;
    }

    @Override
    public Field<Long> field4() {
        return Guilds.GUILDS.REQUEST_CHANNEL_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return Guilds.GUILDS.REQUESTS_ENABLED;
    }

    @Override
    public Field<String> field6() {
        return Guilds.GUILDS.JOIN_MESSAGE;
    }

    @Override
    public Field<Boolean> field7() {
        return Guilds.GUILDS.JOIN_MESSAGES_ENABLED;
    }

    @Override
    public Field<String> field8() {
        return Guilds.GUILDS.LEAVE_MESSAGE;
    }

    @Override
    public Field<Boolean> field9() {
        return Guilds.GUILDS.LEAVE_MESSAGES_ENABLED;
    }

    @Override
    public Field<Long> field10() {
        return Guilds.GUILDS.LOG_CHANNEL_ID;
    }

    @Override
    public Field<Boolean> field11() {
        return Guilds.GUILDS.LOG_MESSAGES_ENABLED;
    }

    @Override
    public Field<Boolean> field12() {
        return Guilds.GUILDS.NSFW_ENABLED;
    }

    @Override
    public Field<Long> field13() {
        return Guilds.GUILDS.INACTIVE_ROLE_ID;
    }

    @Override
    public Field<YearToSecond> field14() {
        return Guilds.GUILDS.INACTIVE_DURATION;
    }

    @Override
    public Field<Long> field15() {
        return Guilds.GUILDS.DJ_ROLE_ID;
    }

    @Override
    public Field<Boolean> field16() {
        return Guilds.GUILDS.SNIPES_ENABLED;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public String component2() {
        return getCommandPrefix();
    }

    @Override
    public Long component3() {
        return getAnnouncementChannelId();
    }

    @Override
    public Long component4() {
        return getRequestChannelId();
    }

    @Override
    public Boolean component5() {
        return getRequestsEnabled();
    }

    @Override
    public String component6() {
        return getJoinMessage();
    }

    @Override
    public Boolean component7() {
        return getJoinMessagesEnabled();
    }

    @Override
    public String component8() {
        return getLeaveMessage();
    }

    @Override
    public Boolean component9() {
        return getLeaveMessagesEnabled();
    }

    @Override
    public Long component10() {
        return getLogChannelId();
    }

    @Override
    public Boolean component11() {
        return getLogMessagesEnabled();
    }

    @Override
    public Boolean component12() {
        return getNsfwEnabled();
    }

    @Override
    public Long component13() {
        return getInactiveRoleId();
    }

    @Override
    public YearToSecond component14() {
        return getInactiveDuration();
    }

    @Override
    public Long component15() {
        return getDjRoleId();
    }

    @Override
    public Boolean component16() {
        return getSnipesEnabled();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public String value2() {
        return getCommandPrefix();
    }

    @Override
    public Long value3() {
        return getAnnouncementChannelId();
    }

    @Override
    public Long value4() {
        return getRequestChannelId();
    }

    @Override
    public Boolean value5() {
        return getRequestsEnabled();
    }

    @Override
    public String value6() {
        return getJoinMessage();
    }

    @Override
    public Boolean value7() {
        return getJoinMessagesEnabled();
    }

    @Override
    public String value8() {
        return getLeaveMessage();
    }

    @Override
    public Boolean value9() {
        return getLeaveMessagesEnabled();
    }

    @Override
    public Long value10() {
        return getLogChannelId();
    }

    @Override
    public Boolean value11() {
        return getLogMessagesEnabled();
    }

    @Override
    public Boolean value12() {
        return getNsfwEnabled();
    }

    @Override
    public Long value13() {
        return getInactiveRoleId();
    }

    @Override
    public YearToSecond value14() {
        return getInactiveDuration();
    }

    @Override
    public Long value15() {
        return getDjRoleId();
    }

    @Override
    public Boolean value16() {
        return getSnipesEnabled();
    }

    @Override
    public GuildsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(String value) {
        setCommandPrefix(value);
        return this;
    }

    @Override
    public GuildsRecord value3(Long value) {
        setAnnouncementChannelId(value);
        return this;
    }

    @Override
    public GuildsRecord value4(Long value) {
        setRequestChannelId(value);
        return this;
    }

    @Override
    public GuildsRecord value5(Boolean value) {
        setRequestsEnabled(value);
        return this;
    }

    @Override
    public GuildsRecord value6(String value) {
        setJoinMessage(value);
        return this;
    }

    @Override
    public GuildsRecord value7(Boolean value) {
        setJoinMessagesEnabled(value);
        return this;
    }

    @Override
    public GuildsRecord value8(String value) {
        setLeaveMessage(value);
        return this;
    }

    @Override
    public GuildsRecord value9(Boolean value) {
        setLeaveMessagesEnabled(value);
        return this;
    }

    @Override
    public GuildsRecord value10(Long value) {
        setLogChannelId(value);
        return this;
    }

    @Override
    public GuildsRecord value11(Boolean value) {
        setLogMessagesEnabled(value);
        return this;
    }

    @Override
    public GuildsRecord value12(Boolean value) {
        setNsfwEnabled(value);
        return this;
    }

    @Override
    public GuildsRecord value13(Long value) {
        setInactiveRoleId(value);
        return this;
    }

    @Override
    public GuildsRecord value14(YearToSecond value) {
        setInactiveDuration(value);
        return this;
    }

    @Override
    public GuildsRecord value15(Long value) {
        setDjRoleId(value);
        return this;
    }

    @Override
    public GuildsRecord value16(Boolean value) {
        setSnipesEnabled(value);
        return this;
    }

    @Override
    public GuildsRecord values(Long value1, String value2, Long value3, Long value4, Boolean value5, String value6, Boolean value7, String value8, Boolean value9, Long value10, Boolean value11, Boolean value12, Long value13, YearToSecond value14, Long value15, Boolean value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildId, String commandPrefix, Long announcementChannelId, Long requestChannelId, Boolean requestsEnabled, String joinMessage, Boolean joinMessagesEnabled, String leaveMessage, Boolean leaveMessagesEnabled, Long logChannelId, Boolean logMessagesEnabled, Boolean nsfwEnabled, Long inactiveRoleId, YearToSecond inactiveDuration, Long djRoleId, Boolean snipesEnabled) {
        super(Guilds.GUILDS);

        setGuildId(guildId);
        setCommandPrefix(commandPrefix);
        setAnnouncementChannelId(announcementChannelId);
        setRequestChannelId(requestChannelId);
        setRequestsEnabled(requestsEnabled);
        setJoinMessage(joinMessage);
        setJoinMessagesEnabled(joinMessagesEnabled);
        setLeaveMessage(leaveMessage);
        setLeaveMessagesEnabled(leaveMessagesEnabled);
        setLogChannelId(logChannelId);
        setLogMessagesEnabled(logMessagesEnabled);
        setNsfwEnabled(nsfwEnabled);
        setInactiveRoleId(inactiveRoleId);
        setInactiveDuration(inactiveDuration);
        setDjRoleId(djRoleId);
        setSnipesEnabled(snipesEnabled);
    }
}
