/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.MemberRoles;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRolesRecord extends UpdatableRecordImpl<MemberRolesRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.member_roles.id</code>.
     */
    public MemberRolesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.member_roles.member_id</code>.
     */
    public MemberRolesRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.member_id</code>.
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.member_roles.role_id</code>.
     */
    public MemberRolesRecord setRoleId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MemberRoles.MEMBER_ROLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return MemberRoles.MEMBER_ROLES.MEMBER_ID;
    }

    @Override
    public Field<Long> field3() {
        return MemberRoles.MEMBER_ROLES.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMemberId();
    }

    @Override
    public Long component3() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMemberId();
    }

    @Override
    public Long value3() {
        return getRoleId();
    }

    @Override
    public MemberRolesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MemberRolesRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    @Override
    public MemberRolesRecord value3(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public MemberRolesRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRolesRecord
     */
    public MemberRolesRecord() {
        super(MemberRoles.MEMBER_ROLES);
    }

    /**
     * Create a detached, initialised MemberRolesRecord
     */
    public MemberRolesRecord(Long id, Long memberId, Long roleId) {
        super(MemberRoles.MEMBER_ROLES);

        setId(id);
        setMemberId(memberId);
        setRoleId(roleId);
    }
}
