/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.MemberRoles;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRolesRecord extends UpdatableRecordImpl<MemberRolesRecord> implements Record4<Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.member_roles.id</code>.
     */
    public MemberRolesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.member_roles.guild_id</code>.
     */
    public MemberRolesRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.member_roles.user_id</code>.
     */
    public MemberRolesRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.member_roles.role_id</code>.
     */
    public MemberRolesRecord setRoleId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.member_roles.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MemberRoles.MEMBER_ROLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return MemberRoles.MEMBER_ROLES.GUILD_ID;
    }

    @Override
    public Field<Long> field3() {
        return MemberRoles.MEMBER_ROLES.USER_ID;
    }

    @Override
    public Field<Long> field4() {
        return MemberRoles.MEMBER_ROLES.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Long component4() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public Long value4() {
        return getRoleId();
    }

    @Override
    public MemberRolesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MemberRolesRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public MemberRolesRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MemberRolesRecord value4(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public MemberRolesRecord values(Long value1, Long value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRolesRecord
     */
    public MemberRolesRecord() {
        super(MemberRoles.MEMBER_ROLES);
    }

    /**
     * Create a detached, initialised MemberRolesRecord
     */
    public MemberRolesRecord(Long id, Long guildId, Long userId, Long roleId) {
        super(MemberRoles.MEMBER_ROLES);

        setId(id);
        setGuildId(guildId);
        setUserId(userId);
        setRoleId(roleId);
    }
}
