/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.Notifications;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> implements Record7<Long, Long, Long, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notifications.id</code>.
     */
    public NotificationsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.notifications.member_id</code>.
     */
    public NotificationsRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.member_id</code>.
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.notifications.channel_id</code>.
     */
    public NotificationsRecord setChannelId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.notifications.message_id</code>.
     */
    public NotificationsRecord setMessageId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.message_id</code>.
     */
    public Long getMessageId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.notifications.content</code>.
     */
    public NotificationsRecord setContent(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.notifications.created_at</code>.
     */
    public NotificationsRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.notifications.notification_time</code>.
     */
    public NotificationsRecord setNotificationTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.notifications.notification_time</code>.
     */
    public LocalDateTime getNotificationTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notifications.NOTIFICATIONS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Notifications.NOTIFICATIONS.MEMBER_ID;
    }

    @Override
    public Field<Long> field3() {
        return Notifications.NOTIFICATIONS.CHANNEL_ID;
    }

    @Override
    public Field<Long> field4() {
        return Notifications.NOTIFICATIONS.MESSAGE_ID;
    }

    @Override
    public Field<String> field5() {
        return Notifications.NOTIFICATIONS.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Notifications.NOTIFICATIONS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Notifications.NOTIFICATIONS.NOTIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMemberId();
    }

    @Override
    public Long component3() {
        return getChannelId();
    }

    @Override
    public Long component4() {
        return getMessageId();
    }

    @Override
    public String component5() {
        return getContent();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getNotificationTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMemberId();
    }

    @Override
    public Long value3() {
        return getChannelId();
    }

    @Override
    public Long value4() {
        return getMessageId();
    }

    @Override
    public String value5() {
        return getContent();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getNotificationTime();
    }

    @Override
    public NotificationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationsRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    @Override
    public NotificationsRecord value3(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public NotificationsRecord value4(Long value) {
        setMessageId(value);
        return this;
    }

    @Override
    public NotificationsRecord value5(String value) {
        setContent(value);
        return this;
    }

    @Override
    public NotificationsRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotificationsRecord value7(LocalDateTime value) {
        setNotificationTime(value);
        return this;
    }

    @Override
    public NotificationsRecord values(Long value1, Long value2, Long value3, Long value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Long id, Long memberId, Long channelId, Long messageId, String content, LocalDateTime createdAt, LocalDateTime notificationTime) {
        super(Notifications.NOTIFICATIONS);

        setId(id);
        setMemberId(memberId);
        setChannelId(channelId);
        setMessageId(messageId);
        setContent(content);
        setCreatedAt(createdAt);
        setNotificationTime(notificationTime);
    }
}
