/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.ReactiveMessages;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReactiveMessagesRecord extends UpdatableRecordImpl<ReactiveMessagesRecord> implements Record6<Long, Long, Long, Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reactive_messages.guild_id</code>.
     */
    public ReactiveMessagesRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.reactive_messages.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reactive_messages.channel_id</code>.
     */
    public ReactiveMessagesRecord setChannelId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.reactive_messages.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.reactive_messages.message_id</code>.
     */
    public ReactiveMessagesRecord setMessageId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.reactive_messages.message_id</code>.
     */
    public Long getMessageId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.reactive_messages.user_id</code>.
     */
    public ReactiveMessagesRecord setUserId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.reactive_messages.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.reactive_messages.command_path</code>.
     */
    public ReactiveMessagesRecord setCommandPath(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.reactive_messages.command_path</code>.
     */
    public String getCommandPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.reactive_messages.allowed</code>.
     */
    public ReactiveMessagesRecord setAllowed(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.reactive_messages.allowed</code>.
     */
    public Long getAllowed() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<Long, Long, Long, Long> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ReactiveMessages.REACTIVE_MESSAGES.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return ReactiveMessages.REACTIVE_MESSAGES.CHANNEL_ID;
    }

    @Override
    public Field<Long> field3() {
        return ReactiveMessages.REACTIVE_MESSAGES.MESSAGE_ID;
    }

    @Override
    public Field<Long> field4() {
        return ReactiveMessages.REACTIVE_MESSAGES.USER_ID;
    }

    @Override
    public Field<String> field5() {
        return ReactiveMessages.REACTIVE_MESSAGES.COMMAND_PATH;
    }

    @Override
    public Field<Long> field6() {
        return ReactiveMessages.REACTIVE_MESSAGES.ALLOWED;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getChannelId();
    }

    @Override
    public Long component3() {
        return getMessageId();
    }

    @Override
    public Long component4() {
        return getUserId();
    }

    @Override
    public String component5() {
        return getCommandPath();
    }

    @Override
    public Long component6() {
        return getAllowed();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getChannelId();
    }

    @Override
    public Long value3() {
        return getMessageId();
    }

    @Override
    public Long value4() {
        return getUserId();
    }

    @Override
    public String value5() {
        return getCommandPath();
    }

    @Override
    public Long value6() {
        return getAllowed();
    }

    @Override
    public ReactiveMessagesRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public ReactiveMessagesRecord value2(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public ReactiveMessagesRecord value3(Long value) {
        setMessageId(value);
        return this;
    }

    @Override
    public ReactiveMessagesRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public ReactiveMessagesRecord value5(String value) {
        setCommandPath(value);
        return this;
    }

    @Override
    public ReactiveMessagesRecord value6(Long value) {
        setAllowed(value);
        return this;
    }

    @Override
    public ReactiveMessagesRecord values(Long value1, Long value2, Long value3, Long value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReactiveMessagesRecord
     */
    public ReactiveMessagesRecord() {
        super(ReactiveMessages.REACTIVE_MESSAGES);
    }

    /**
     * Create a detached, initialised ReactiveMessagesRecord
     */
    public ReactiveMessagesRecord(Long guildId, Long channelId, Long messageId, Long userId, String commandPath, Long allowed) {
        super(ReactiveMessages.REACTIVE_MESSAGES);

        setGuildId(guildId);
        setChannelId(channelId);
        setMessageId(messageId);
        setUserId(userId);
        setCommandPath(commandPath);
        setAllowed(allowed);
    }
}
