/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.SelfAssignableRoles;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SelfAssignableRolesRecord extends UpdatableRecordImpl<SelfAssignableRolesRecord> implements Record3<Long, Long, Long>{

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached SelfAssignableRolesRecord
	 */
	public SelfAssignableRolesRecord(){
		super(SelfAssignableRoles.SELF_ASSIGNABLE_ROLES);
	}

	/**
	 * Create a detached, initialised SelfAssignableRolesRecord
	 */
	public SelfAssignableRolesRecord(Long roleId, Long guildId, Long emoteId){
		super(SelfAssignableRoles.SELF_ASSIGNABLE_ROLES);

		setRoleId(roleId);
		setGuildId(guildId);
		setEmoteId(emoteId);
	}

	@Override
	public Record2<Long, Long> key(){
		return (Record2) super.key();
	}

	@Override
	public Row3<Long, Long, Long> fieldsRow(){
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<Long, Long, Long> valuesRow(){
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<Long> field1(){
		return SelfAssignableRoles.SELF_ASSIGNABLE_ROLES.ROLE_ID;
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Field<Long> field2(){
		return SelfAssignableRoles.SELF_ASSIGNABLE_ROLES.GUILD_ID;
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Field<Long> field3(){
		return SelfAssignableRoles.SELF_ASSIGNABLE_ROLES.EMOTE_ID;
	}

	@Override
	public Long value1(){
		return getRoleId();
	}

	@Override
	public Long value2(){
		return getGuildId();
	}

	@Override
	public Long value3(){
		return getEmoteId();
	}

	@Override
	public SelfAssignableRolesRecord value1(Long value){
		setRoleId(value);
		return this;
	}

	@Override
	public SelfAssignableRolesRecord value2(Long value){
		setGuildId(value);
		return this;
	}

	@Override
	public SelfAssignableRolesRecord value3(Long value){
		setEmoteId(value);
		return this;
	}

	@Override
	public SelfAssignableRolesRecord values(Long value1, Long value2, Long value3){
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	@Override
	public Long component1(){
		return getRoleId();
	}

	@Override
	public Long component2(){
		return getGuildId();
	}

	@Override
	public Long component3(){
		return getEmoteId();
	}

	/**
	 * Getter for <code>public.self_assignable_roles.emote_id</code>.
	 */
	public Long getEmoteId(){
		return (Long) get(2);
	}

	/**
	 * Setter for <code>public.self_assignable_roles.emote_id</code>.
	 */
	public SelfAssignableRolesRecord setEmoteId(Long value){
		set(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.self_assignable_roles.guild_id</code>.
	 */
	public Long getGuildId(){
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.self_assignable_roles.guild_id</code>.
	 */
	public SelfAssignableRolesRecord setGuildId(Long value){
		set(1, value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.self_assignable_roles.role_id</code>.
	 */
	public Long getRoleId(){
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.self_assignable_roles.role_id</code>.
	 */
	public SelfAssignableRolesRecord setRoleId(Long value){
		set(0, value);
		return this;
	}

}
