/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.SnipeDisabledChannels;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SnipeDisabledChannelsRecord extends UpdatableRecordImpl<SnipeDisabledChannelsRecord> implements Record3<Long, Long, Long>{

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached SnipeDisabledChannelsRecord
	 */
	public SnipeDisabledChannelsRecord(){
		super(SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS);
	}

	/**
	 * Create a detached, initialised SnipeDisabledChannelsRecord
	 */
	public SnipeDisabledChannelsRecord(Long snipeDisabledChannelId, Long guildId, Long channelId){
		super(SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS);

		setSnipeDisabledChannelId(snipeDisabledChannelId);
		setGuildId(guildId);
		setChannelId(channelId);
	}

	@Override
	public Record1<Long> key(){
		return (Record1) super.key();
	}

	@Override
	public Row3<Long, Long, Long> fieldsRow(){
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<Long, Long, Long> valuesRow(){
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<Long> field1(){
		return SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS.SNIPE_DISABLED_CHANNEL_ID;
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Field<Long> field2(){
		return SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS.GUILD_ID;
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Field<Long> field3(){
		return SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS.CHANNEL_ID;
	}

	@Override
	public Long value1(){
		return getSnipeDisabledChannelId();
	}

	@Override
	public Long value2(){
		return getGuildId();
	}

	@Override
	public Long value3(){
		return getChannelId();
	}

	@Override
	public SnipeDisabledChannelsRecord value1(Long value){
		setSnipeDisabledChannelId(value);
		return this;
	}

	@Override
	public SnipeDisabledChannelsRecord value2(Long value){
		setGuildId(value);
		return this;
	}

	@Override
	public SnipeDisabledChannelsRecord value3(Long value){
		setChannelId(value);
		return this;
	}

	@Override
	public SnipeDisabledChannelsRecord values(Long value1, Long value2, Long value3){
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	@Override
	public Long component1(){
		return getSnipeDisabledChannelId();
	}

	/**
	 * Getter for <code>public.snipe_disabled_channels.snipe_disabled_channel_id</code>.
	 */
	public Long getSnipeDisabledChannelId(){
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.snipe_disabled_channels.snipe_disabled_channel_id</code>.
	 */
	public SnipeDisabledChannelsRecord setSnipeDisabledChannelId(Long value){
		set(0, value);
		return this;
	}

	@Override
	public Long component2(){
		return getGuildId();
	}

	/**
	 * Getter for <code>public.snipe_disabled_channels.guild_id</code>.
	 */
	public Long getGuildId(){
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.snipe_disabled_channels.guild_id</code>.
	 */
	public SnipeDisabledChannelsRecord setGuildId(Long value){
		set(1, value);
		return this;
	}

	@Override
	public Long component3(){
		return getChannelId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.snipe_disabled_channels.channel_id</code>.
	 */
	public Long getChannelId(){
		return (Long) get(2);
	}

	/**
	 * Setter for <code>public.snipe_disabled_channels.channel_id</code>.
	 */
	public SnipeDisabledChannelsRecord setChannelId(Long value){
		set(2, value);
		return this;
	}

}
