/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.UserStatistics;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStatisticsRecord extends UpdatableRecordImpl<UserStatisticsRecord> implements Record10<Long, Long, Long, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_statistics.user_statistic_id</code>.
     */
    public UserStatisticsRecord setUserStatisticId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.user_statistic_id</code>.
     */
    public Long getUserStatisticId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_statistics.user_id</code>.
     */
    public UserStatisticsRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_statistics.guild_id</code>.
     */
    public UserStatisticsRecord setGuildId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_statistics.xp</code>.
     */
    public UserStatisticsRecord setXp(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.xp</code>.
     */
    public Integer getXp() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.user_statistics.level</code>.
     */
    public UserStatisticsRecord setLevel(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.user_statistics.bot_calls</code>.
     */
    public UserStatisticsRecord setBotCalls(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.bot_calls</code>.
     */
    public Integer getBotCalls() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.user_statistics.voice_time</code>.
     */
    public UserStatisticsRecord setVoiceTime(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.voice_time</code>.
     */
    public Integer getVoiceTime() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.user_statistics.message_count</code>.
     */
    public UserStatisticsRecord setMessageCount(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.message_count</code>.
     */
    public Integer getMessageCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.user_statistics.emote_count</code>.
     */
    public UserStatisticsRecord setEmoteCount(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.emote_count</code>.
     */
    public Integer getEmoteCount() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.user_statistics.last_active</code>.
     */
    public UserStatisticsRecord setLastActive(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.last_active</code>.
     */
    public LocalDateTime getLastActive() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Long, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserStatistics.USER_STATISTICS.USER_STATISTIC_ID;
    }

    @Override
    public Field<Long> field2() {
        return UserStatistics.USER_STATISTICS.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserStatistics.USER_STATISTICS.GUILD_ID;
    }

    @Override
    public Field<Integer> field4() {
        return UserStatistics.USER_STATISTICS.XP;
    }

    @Override
    public Field<Integer> field5() {
        return UserStatistics.USER_STATISTICS.LEVEL;
    }

    @Override
    public Field<Integer> field6() {
        return UserStatistics.USER_STATISTICS.BOT_CALLS;
    }

    @Override
    public Field<Integer> field7() {
        return UserStatistics.USER_STATISTICS.VOICE_TIME;
    }

    @Override
    public Field<Integer> field8() {
        return UserStatistics.USER_STATISTICS.MESSAGE_COUNT;
    }

    @Override
    public Field<Integer> field9() {
        return UserStatistics.USER_STATISTICS.EMOTE_COUNT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return UserStatistics.USER_STATISTICS.LAST_ACTIVE;
    }

    @Override
    public Long component1() {
        return getUserStatisticId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getGuildId();
    }

    @Override
    public Integer component4() {
        return getXp();
    }

    @Override
    public Integer component5() {
        return getLevel();
    }

    @Override
    public Integer component6() {
        return getBotCalls();
    }

    @Override
    public Integer component7() {
        return getVoiceTime();
    }

    @Override
    public Integer component8() {
        return getMessageCount();
    }

    @Override
    public Integer component9() {
        return getEmoteCount();
    }

    @Override
    public LocalDateTime component10() {
        return getLastActive();
    }

    @Override
    public Long value1() {
        return getUserStatisticId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getGuildId();
    }

    @Override
    public Integer value4() {
        return getXp();
    }

    @Override
    public Integer value5() {
        return getLevel();
    }

    @Override
    public Integer value6() {
        return getBotCalls();
    }

    @Override
    public Integer value7() {
        return getVoiceTime();
    }

    @Override
    public Integer value8() {
        return getMessageCount();
    }

    @Override
    public Integer value9() {
        return getEmoteCount();
    }

    @Override
    public LocalDateTime value10() {
        return getLastActive();
    }

    @Override
    public UserStatisticsRecord value1(Long value) {
        setUserStatisticId(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value3(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value4(Integer value) {
        setXp(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value5(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value6(Integer value) {
        setBotCalls(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value7(Integer value) {
        setVoiceTime(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value8(Integer value) {
        setMessageCount(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value9(Integer value) {
        setEmoteCount(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value10(LocalDateTime value) {
        setLastActive(value);
        return this;
    }

    @Override
    public UserStatisticsRecord values(Long value1, Long value2, Long value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserStatisticsRecord
     */
    public UserStatisticsRecord() {
        super(UserStatistics.USER_STATISTICS);
    }

    /**
     * Create a detached, initialised UserStatisticsRecord
     */
    public UserStatisticsRecord(Long userStatisticId, Long userId, Long guildId, Integer xp, Integer level, Integer botCalls, Integer voiceTime, Integer messageCount, Integer emoteCount, LocalDateTime lastActive) {
        super(UserStatistics.USER_STATISTICS);

        setUserStatisticId(userStatisticId);
        setUserId(userId);
        setGuildId(guildId);
        setXp(xp);
        setLevel(level);
        setBotCalls(botCalls);
        setVoiceTime(voiceTime);
        setMessageCount(messageCount);
        setEmoteCount(emoteCount);
        setLastActive(lastActive);
    }
}
