CREATE TABLE IF NOT EXISTS members(
  id       BIGSERIAL PRIMARY KEY NOT NULL,
  user_id  BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  guild_id BIGINT NOT NULL UNIQUE REFERENCES guilds(id) ON DELETE CASCADE
);
