CREATE TABLE IF NOT EXISTS member_roles(
  id       BIGSERIAL PRIMARY KEY NOT NULL,
  guild_id BIGINT NOT NULL UNIQUE REFERENCES guilds(id) ON DELETE CASCADE,
  user_id  BIGINT NOT NULL UNIQUE,
  role_id  BIGINT NOT NULL UNIQUE
);