/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotDisabledChannels implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long guildId;
    private final Long channelId;

    public BotDisabledChannels(BotDisabledChannels value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.channelId = value.channelId;
    }

    public BotDisabledChannels(
        Long id,
        Long guildId,
        Long channelId
    ) {
        this.id = id;
        this.guildId = guildId;
        this.channelId = channelId;
    }

    /**
     * Getter for <code>public.bot_disabled_channels.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.bot_disabled_channels.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.bot_disabled_channels.channel_id</code>.
     */
    public Long getChannelId() {
        return this.channelId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BotDisabledChannels (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(channelId);

        sb.append(")");
        return sb.toString();
    }
}
