/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotIgnoredMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long guildId;
    private final Long userId;

    public BotIgnoredMembers(BotIgnoredMembers value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.userId = value.userId;
    }

    public BotIgnoredMembers(
        Long id,
        Long guildId,
        Long userId
    ) {
        this.id = id;
        this.guildId = guildId;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.bot_ignored_members.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.bot_ignored_members.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.bot_ignored_members.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BotIgnoredMembers (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
