/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotIgnoredUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long botIgnoredUserId;
    private final Long guildId;
    private final Long userId;

    public BotIgnoredUsers(BotIgnoredUsers value) {
        this.botIgnoredUserId = value.botIgnoredUserId;
        this.guildId = value.guildId;
        this.userId = value.userId;
    }

    public BotIgnoredUsers(
        Long botIgnoredUserId,
        Long guildId,
        Long userId
    ) {
        this.botIgnoredUserId = botIgnoredUserId;
        this.guildId = guildId;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.bot_ignored_users.bot_ignored_user_id</code>.
     */
    public Long getBotIgnoredUserId() {
        return this.botIgnoredUserId;
    }

    /**
     * Getter for <code>public.bot_ignored_users.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.bot_ignored_users.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BotIgnoredUsers (");

        sb.append(botIgnoredUserId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
