/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotIgnoredMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long memberId;

    public BotIgnoredMembers(BotIgnoredMembers value) {
        this.id = value.id;
        this.memberId = value.memberId;
    }

    public BotIgnoredMembers(
        Long id,
        Long memberId
    ) {
        this.id = id;
        this.memberId = memberId;
    }

    /**
     * Getter for <code>public.bot_ignored_members.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.bot_ignored_members.member_id</code>.
     */
    public Long getMemberId() {
        return this.memberId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BotIgnoredMembers (");

        sb.append(id);
        sb.append(", ").append(memberId);

        sb.append(")");
        return sb.toString();
    }
}
