/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long guildId;
    private final Long userId;
    private final Long roleId;

    public MemberRoles(MemberRoles value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public MemberRoles(
        Long id,
        Long guildId,
        Long userId,
        Long roleId
    ) {
        this.id = id;
        this.guildId = guildId;
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * Getter for <code>public.member_roles.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.member_roles.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.member_roles.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.member_roles.role_id</code>.
     */
    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MemberRoles (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
