/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Members implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long userId;
    private final Long guildId;

    public Members(Members value) {
        this.id = value.id;
        this.userId = value.userId;
        this.guildId = value.guildId;
    }

    public Members(
        Long id,
        Long userId,
        Long guildId
    ) {
        this.id = id;
        this.userId = userId;
        this.guildId = guildId;
    }

    /**
     * Getter for <code>public.members.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.members.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.members.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Members (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(guildId);

        sb.append(")");
        return sb.toString();
    }
}
