/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReactiveMessages implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   guildId;
    private final Long   channelId;
    private final Long   messageId;
    private final Long   userId;
    private final String commandPath;
    private final Long   allowed;

    public ReactiveMessages(ReactiveMessages value) {
        this.guildId = value.guildId;
        this.channelId = value.channelId;
        this.messageId = value.messageId;
        this.userId = value.userId;
        this.commandPath = value.commandPath;
        this.allowed = value.allowed;
    }

    public ReactiveMessages(
        Long   guildId,
        Long   channelId,
        Long   messageId,
        Long   userId,
        String commandPath,
        Long   allowed
    ) {
        this.guildId = guildId;
        this.channelId = channelId;
        this.messageId = messageId;
        this.userId = userId;
        this.commandPath = commandPath;
        this.allowed = allowed;
    }

    /**
     * Getter for <code>public.reactive_messages.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.reactive_messages.channel_id</code>.
     */
    public Long getChannelId() {
        return this.channelId;
    }

    /**
     * Getter for <code>public.reactive_messages.message_id</code>.
     */
    public Long getMessageId() {
        return this.messageId;
    }

    /**
     * Getter for <code>public.reactive_messages.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.reactive_messages.command_path</code>.
     */
    public String getCommandPath() {
        return this.commandPath;
    }

    /**
     * Getter for <code>public.reactive_messages.allowed</code>.
     */
    public Long getAllowed() {
        return this.allowed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReactiveMessages (");

        sb.append(guildId);
        sb.append(", ").append(channelId);
        sb.append(", ").append(messageId);
        sb.append(", ").append(userId);
        sb.append(", ").append(commandPath);
        sb.append(", ").append(allowed);

        sb.append(")");
        return sb.toString();
    }
}
