/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SelfAssignableRoles implements Serializable{

	private static final long serialVersionUID = 1L;

	private final Long roleId;
	private final Long guildId;
	private final Long emoteId;

	public SelfAssignableRoles(SelfAssignableRoles value){
		this.roleId = value.roleId;
		this.guildId = value.guildId;
		this.emoteId = value.emoteId;
	}

	public SelfAssignableRoles(
			Long roleId,
			Long guildId,
			Long emoteId
	){
		this.roleId = roleId;
		this.guildId = guildId;
		this.emoteId = emoteId;
	}

	/**
	 * Getter for <code>public.self_assignable_roles.role_id</code>.
	 */
	public Long getRoleId(){
		return this.roleId;
	}

	/**
	 * Getter for <code>public.self_assignable_roles.guild_id</code>.
	 */
	public Long getGuildId(){
		return this.guildId;
	}

	/**
	 * Getter for <code>public.self_assignable_roles.emote_id</code>.
	 */
	public Long getEmoteId(){
		return this.emoteId;
	}

	@Override
	public String toString(){
		StringBuilder sb = new StringBuilder("SelfAssignableRoles (");

		sb.append(roleId);
		sb.append(", ").append(guildId);
		sb.append(", ").append(emoteId);

		sb.append(")");
		return sb.toString();
	}

}
