/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long    id;
    private final Long    guildId;
    private final String  userName;
    private final Integer streamType;

    public StreamUsers(StreamUsers value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.userName = value.userName;
        this.streamType = value.streamType;
    }

    public StreamUsers(
        Long    id,
        Long    guildId,
        String  userName,
        Integer streamType
    ) {
        this.id = id;
        this.guildId = guildId;
        this.userName = userName;
        this.streamType = streamType;
    }

    /**
     * Getter for <code>public.stream_users.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.stream_users.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.stream_users.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Getter for <code>public.stream_users.stream_type</code>.
     */
    public Integer getStreamType() {
        return this.streamType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StreamUsers (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(userName);
        sb.append(", ").append(streamType);

        sb.append(")");
        return sb.toString();
    }
}
