/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.records;


import de.kittybot.kittybot.database.jooq.tables.Commands;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.YearToSecond;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommandsRecord extends TableRecordImpl<CommandsRecord> implements Record6<String, String, String, String, YearToSecond, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.commands.message_id</code>.
     */
    public CommandsRecord setMessageId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.commands.message_id</code>.
     */
    public String getMessageId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.commands.guild_id</code>.
     */
    public CommandsRecord setGuildId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.commands.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.commands.user_id</code>.
     */
    public CommandsRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.commands.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.commands.command</code>.
     */
    public CommandsRecord setCommand(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.commands.command</code>.
     */
    public String getCommand() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.commands.processing_time</code>.
     */
    public CommandsRecord setProcessingTime(YearToSecond value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.commands.processing_time</code>.
     */
    public YearToSecond getProcessingTime() {
        return (YearToSecond) get(4);
    }

    /**
     * Setter for <code>public.commands.time</code>.
     */
    public CommandsRecord setTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.commands.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, YearToSecond, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, YearToSecond, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Commands.COMMANDS.MESSAGE_ID;
    }

    @Override
    public Field<String> field2() {
        return Commands.COMMANDS.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return Commands.COMMANDS.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return Commands.COMMANDS.COMMAND;
    }

    @Override
    public Field<YearToSecond> field5() {
        return Commands.COMMANDS.PROCESSING_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Commands.COMMANDS.TIME;
    }

    @Override
    public String component1() {
        return getMessageId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getCommand();
    }

    @Override
    public YearToSecond component5() {
        return getProcessingTime();
    }

    @Override
    public LocalDateTime component6() {
        return getTime();
    }

    @Override
    public String value1() {
        return getMessageId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getCommand();
    }

    @Override
    public YearToSecond value5() {
        return getProcessingTime();
    }

    @Override
    public LocalDateTime value6() {
        return getTime();
    }

    @Override
    public CommandsRecord value1(String value) {
        setMessageId(value);
        return this;
    }

    @Override
    public CommandsRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public CommandsRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public CommandsRecord value4(String value) {
        setCommand(value);
        return this;
    }

    @Override
    public CommandsRecord value5(YearToSecond value) {
        setProcessingTime(value);
        return this;
    }

    @Override
    public CommandsRecord value6(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public CommandsRecord values(String value1, String value2, String value3, String value4, YearToSecond value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommandsRecord
     */
    public CommandsRecord() {
        super(Commands.COMMANDS);
    }

    /**
     * Create a detached, initialised CommandsRecord
     */
    public CommandsRecord(String messageId, String guildId, String userId, String command, YearToSecond processingTime, LocalDateTime time) {
        super(Commands.COMMANDS);

        setMessageId(messageId);
        setGuildId(guildId);
        setUserId(userId);
        setCommand(command);
        setProcessingTime(processingTime);
        setTime(time);
    }
}
