/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.records;


import de.kittybot.kittybot.database.jooq.tables.SelfAssignableRoleGroups;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelfAssignableRoleGroupsRecord extends UpdatableRecordImpl<SelfAssignableRoleGroupsRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = -1699549042;

    /**
     * Setter for <code>public.self_assignable_role_groups.group_id</code>.
     */
    public SelfAssignableRoleGroupsRecord setGroupId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.self_assignable_role_groups.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.self_assignable_role_groups.guild_id</code>.
     */
    public SelfAssignableRoleGroupsRecord setGuildId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.self_assignable_role_groups.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.self_assignable_role_groups.group_name</code>.
     */
    public SelfAssignableRoleGroupsRecord setGroupName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.self_assignable_role_groups.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.self_assignable_role_groups.max_roles</code>.
     */
    public SelfAssignableRoleGroupsRecord setMaxRoles(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.self_assignable_role_groups.max_roles</code>.
     */
    public Integer getMaxRoles() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS.GROUP_ID;
    }

    @Override
    public Field<String> field2() {
        return SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS.GROUP_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS.MAX_ROLES;
    }

    @Override
    public Integer component1() {
        return getGroupId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getGroupName();
    }

    @Override
    public Integer component4() {
        return getMaxRoles();
    }

    @Override
    public Integer value1() {
        return getGroupId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getGroupName();
    }

    @Override
    public Integer value4() {
        return getMaxRoles();
    }

    @Override
    public SelfAssignableRoleGroupsRecord value1(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public SelfAssignableRoleGroupsRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public SelfAssignableRoleGroupsRecord value3(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public SelfAssignableRoleGroupsRecord value4(Integer value) {
        setMaxRoles(value);
        return this;
    }

    @Override
    public SelfAssignableRoleGroupsRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelfAssignableRoleGroupsRecord
     */
    public SelfAssignableRoleGroupsRecord() {
        super(SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS);
    }

    /**
     * Create a detached, initialised SelfAssignableRoleGroupsRecord
     */
    public SelfAssignableRoleGroupsRecord(Integer groupId, String guildId, String groupName, Integer maxRoles) {
        super(SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS);

        set(0, groupId);
        set(1, guildId);
        set(2, groupName);
        set(3, maxRoles);
    }
}
