/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq.tables.records;


import de.kittybot.kittybot.database.jooq.tables.Sessions;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SessionsRecord extends UpdatableRecordImpl<SessionsRecord> implements Record2<String, String>{

	private static final long serialVersionUID = -1306661103;

	/**
	 * Create a detached SessionsRecord
	 */
	public SessionsRecord(){
		super(Sessions.SESSIONS);
	}

	/**
	 * Create a detached, initialised SessionsRecord
	 */
	public SessionsRecord(String sessionId, String userId){
		super(Sessions.SESSIONS);

		set(0, sessionId);
		set(1, userId);
	}

	@Override
	public Record1<String> key(){
		return (Record1) super.key();
	}

	@Override
	public Row2<String, String> fieldsRow(){
		return (Row2) super.fieldsRow();
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Row2<String, String> valuesRow(){
		return (Row2) super.valuesRow();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Field<String> field1(){
		return Sessions.SESSIONS.SESSION_ID;
	}

	@Override
	public Field<String> field2(){
		return Sessions.SESSIONS.USER_ID;
	}

	@Override
	public String value1(){
		return getSessionId();
	}

	@Override
	public String value2(){
		return getUserId();
	}

	@Override
	public SessionsRecord value1(String value){
		setSessionId(value);
		return this;
	}

	@Override
	public SessionsRecord value2(String value){
		setUserId(value);
		return this;
	}

	@Override
	public SessionsRecord values(String value1, String value2){
		value1(value1);
		value2(value2);
		return this;
	}

	@Override
	public String component1(){
		return getSessionId();
	}

	@Override
	public String component2(){
		return getUserId();
	}

	/**
	 * Getter for <code>public.sessions.user_id</code>.
	 */
	public String getUserId(){
		return (String) get(1);
	}

	/**
	 * Setter for <code>public.sessions.user_id</code>.
	 */
	public SessionsRecord setUserId(String value){
		set(1, value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.sessions.session_id</code>.
	 */
	public String getSessionId(){
		return (String) get(0);
	}

	/**
	 * Setter for <code>public.sessions.session_id</code>.
	 */
	public SessionsRecord setSessionId(String value){
		set(0, value);
		return this;
	}

}
