/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.database.jooq;


import de.kittybot.kittybot.database.jooq.tables.Commands;
import de.kittybot.kittybot.database.jooq.tables.Guilds;
import de.kittybot.kittybot.database.jooq.tables.ReactiveMessages;
import de.kittybot.kittybot.database.jooq.tables.SelfAssignableRoleGroups;
import de.kittybot.kittybot.database.jooq.tables.SelfAssignableRoles;
import de.kittybot.kittybot.database.jooq.tables.Sessions;
import de.kittybot.kittybot.database.jooq.tables.UserStatistics;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.commands</code>.
     */
    public static final Commands COMMANDS = Commands.COMMANDS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.reactive_messages</code>.
     */
    public static final ReactiveMessages REACTIVE_MESSAGES = ReactiveMessages.REACTIVE_MESSAGES;

    /**
     * The table <code>public.self_assignable_role_groups</code>.
     */
    public static final SelfAssignableRoleGroups SELF_ASSIGNABLE_ROLE_GROUPS = SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS;

    /**
     * The table <code>public.self_assignable_roles</code>.
     */
    public static final SelfAssignableRoles SELF_ASSIGNABLE_ROLES = SelfAssignableRoles.SELF_ASSIGNABLE_ROLES;

    /**
     * The table <code>public.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.user_statistics</code>.
     */
    public static final UserStatistics USER_STATISTICS = UserStatistics.USER_STATISTICS;
}
