/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.BotIgnoredMembers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotIgnoredMembersRecord extends UpdatableRecordImpl<BotIgnoredMembersRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bot_ignored_members.id</code>.
     */
    public BotIgnoredMembersRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bot_ignored_members.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bot_ignored_members.guild_id</code>.
     */
    public BotIgnoredMembersRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bot_ignored_members.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.bot_ignored_members.user_id</code>.
     */
    public BotIgnoredMembersRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bot_ignored_members.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BotIgnoredMembers.BOT_IGNORED_MEMBERS.ID;
    }

    @Override
    public Field<Long> field2() {
        return BotIgnoredMembers.BOT_IGNORED_MEMBERS.GUILD_ID;
    }

    @Override
    public Field<Long> field3() {
        return BotIgnoredMembers.BOT_IGNORED_MEMBERS.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public BotIgnoredMembersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BotIgnoredMembersRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public BotIgnoredMembersRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public BotIgnoredMembersRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BotIgnoredMembersRecord
     */
    public BotIgnoredMembersRecord() {
        super(BotIgnoredMembers.BOT_IGNORED_MEMBERS);
    }

    /**
     * Create a detached, initialised BotIgnoredMembersRecord
     */
    public BotIgnoredMembersRecord(Long id, Long guildId, Long userId) {
        super(BotIgnoredMembers.BOT_IGNORED_MEMBERS);

        setId(id);
        setGuildId(guildId);
        setUserId(userId);
    }
}
