/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq.tables.records;


import de.kittybot.kittybot.jooq.tables.UserStatistics;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.YearToSecond;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStatisticsRecord extends UpdatableRecordImpl<UserStatisticsRecord> implements Record9<Long, Long, Long, Long, Integer, YearToSecond, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_statistics.id</code>.
     */
    public UserStatisticsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_statistics.guild_id</code>.
     */
    public UserStatisticsRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_statistics.user_id</code>.
     */
    public UserStatisticsRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_statistics.xp</code>.
     */
    public UserStatisticsRecord setXp(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.xp</code>.
     */
    public Long getXp() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.user_statistics.bot_calls</code>.
     */
    public UserStatisticsRecord setBotCalls(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.bot_calls</code>.
     */
    public Integer getBotCalls() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.user_statistics.voice_time</code>.
     */
    public UserStatisticsRecord setVoiceTime(YearToSecond value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.voice_time</code>.
     */
    public YearToSecond getVoiceTime() {
        return (YearToSecond) get(5);
    }

    /**
     * Setter for <code>public.user_statistics.message_count</code>.
     */
    public UserStatisticsRecord setMessageCount(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.message_count</code>.
     */
    public Integer getMessageCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.user_statistics.emote_count</code>.
     */
    public UserStatisticsRecord setEmoteCount(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.emote_count</code>.
     */
    public Integer getEmoteCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.user_statistics.last_active</code>.
     */
    public UserStatisticsRecord setLastActive(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.user_statistics.last_active</code>.
     */
    public LocalDateTime getLastActive() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, Integer, YearToSecond, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Long, Long, Integer, YearToSecond, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserStatistics.USER_STATISTICS.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserStatistics.USER_STATISTICS.GUILD_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserStatistics.USER_STATISTICS.USER_ID;
    }

    @Override
    public Field<Long> field4() {
        return UserStatistics.USER_STATISTICS.XP;
    }

    @Override
    public Field<Integer> field5() {
        return UserStatistics.USER_STATISTICS.BOT_CALLS;
    }

    @Override
    public Field<YearToSecond> field6() {
        return UserStatistics.USER_STATISTICS.VOICE_TIME;
    }

    @Override
    public Field<Integer> field7() {
        return UserStatistics.USER_STATISTICS.MESSAGE_COUNT;
    }

    @Override
    public Field<Integer> field8() {
        return UserStatistics.USER_STATISTICS.EMOTE_COUNT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return UserStatistics.USER_STATISTICS.LAST_ACTIVE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Long component4() {
        return getXp();
    }

    @Override
    public Integer component5() {
        return getBotCalls();
    }

    @Override
    public YearToSecond component6() {
        return getVoiceTime();
    }

    @Override
    public Integer component7() {
        return getMessageCount();
    }

    @Override
    public Integer component8() {
        return getEmoteCount();
    }

    @Override
    public LocalDateTime component9() {
        return getLastActive();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public Long value4() {
        return getXp();
    }

    @Override
    public Integer value5() {
        return getBotCalls();
    }

    @Override
    public YearToSecond value6() {
        return getVoiceTime();
    }

    @Override
    public Integer value7() {
        return getMessageCount();
    }

    @Override
    public Integer value8() {
        return getEmoteCount();
    }

    @Override
    public LocalDateTime value9() {
        return getLastActive();
    }

    @Override
    public UserStatisticsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value4(Long value) {
        setXp(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value5(Integer value) {
        setBotCalls(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value6(YearToSecond value) {
        setVoiceTime(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value7(Integer value) {
        setMessageCount(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value8(Integer value) {
        setEmoteCount(value);
        return this;
    }

    @Override
    public UserStatisticsRecord value9(LocalDateTime value) {
        setLastActive(value);
        return this;
    }

    @Override
    public UserStatisticsRecord values(Long value1, Long value2, Long value3, Long value4, Integer value5, YearToSecond value6, Integer value7, Integer value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserStatisticsRecord
     */
    public UserStatisticsRecord() {
        super(UserStatistics.USER_STATISTICS);
    }

    /**
     * Create a detached, initialised UserStatisticsRecord
     */
    public UserStatisticsRecord(Long id, Long guildId, Long userId, Long xp, Integer botCalls, YearToSecond voiceTime, Integer messageCount, Integer emoteCount, LocalDateTime lastActive) {
        super(UserStatistics.USER_STATISTICS);

        setId(id);
        setGuildId(guildId);
        setUserId(userId);
        setXp(xp);
        setBotCalls(botCalls);
        setVoiceTime(voiceTime);
        setMessageCount(messageCount);
        setEmoteCount(emoteCount);
        setLastActive(lastActive);
    }
}
