/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq;


import de.kittybot.kittybot.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl{

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();
	private static final long serialVersionUID = 1L;
	/**
	 * The table <code>public.bot_disabled_channels</code>.
	 */
	public final BotDisabledChannels BOT_DISABLED_CHANNELS = BotDisabledChannels.BOT_DISABLED_CHANNELS;

	/**
	 * The table <code>public.guilds</code>.
	 */
	public final Guilds GUILDS = Guilds.GUILDS;

	/**
	 * The table <code>public.reactive_messages</code>.
	 */
	public final ReactiveMessages REACTIVE_MESSAGES = ReactiveMessages.REACTIVE_MESSAGES;

	/**
	 * The table <code>public.self_assignable_roles</code>.
	 */
	public final SelfAssignableRoles SELF_ASSIGNABLE_ROLES = SelfAssignableRoles.SELF_ASSIGNABLE_ROLES;

	/**
	 * The table <code>public.sessions</code>.
	 */
	public final Sessions SESSIONS = Sessions.SESSIONS;

	/**
	 * The table <code>public.snipe_disabled_channels</code>.
	 */
	public final SnipeDisabledChannels SNIPE_DISABLED_CHANNELS = SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS;

	/**
	 * No further instances allowed
	 */
	private Public(){
		super("public", null);
	}


	@Override
	public Catalog getCatalog(){
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables(){
		return Arrays.<Table<?>>asList(
				BotDisabledChannels.BOT_DISABLED_CHANNELS,
				Guilds.GUILDS,
				ReactiveMessages.REACTIVE_MESSAGES,
				SelfAssignableRoles.SELF_ASSIGNABLE_ROLES,
				Sessions.SESSIONS,
				SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS);
	}

}
