/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq;


import de.kittybot.kittybot.jooq.tables.Guilds;
import de.kittybot.kittybot.jooq.tables.ReactiveMessages;
import de.kittybot.kittybot.jooq.tables.SelfAssignableRoles;
import de.kittybot.kittybot.jooq.tables.Sessions;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables{

	/**
	 * The table <code>public.guilds</code>.
	 */
	public static final Guilds GUILDS = Guilds.GUILDS;

	/**
	 * The table <code>public.reactive_messages</code>.
	 */
	public static final ReactiveMessages REACTIVE_MESSAGES = ReactiveMessages.REACTIVE_MESSAGES;

	/**
	 * The table <code>public.self_assignable_roles</code>.
	 */
	public static final SelfAssignableRoles SELF_ASSIGNABLE_ROLES = SelfAssignableRoles.SELF_ASSIGNABLE_ROLES;

	/**
	 * The table <code>public.sessions</code>.
	 */
	public static final Sessions SESSIONS = Sessions.SESSIONS;

}
