/*
 * This file is generated by jOOQ.
 */
package de.kittybot.kittybot.jooq;


import de.kittybot.kittybot.jooq.tables.BotDisabledChannels;
import de.kittybot.kittybot.jooq.tables.BotIgnoredMembers;
import de.kittybot.kittybot.jooq.tables.GuildInviteRoles;
import de.kittybot.kittybot.jooq.tables.GuildInvites;
import de.kittybot.kittybot.jooq.tables.GuildTags;
import de.kittybot.kittybot.jooq.tables.Guilds;
import de.kittybot.kittybot.jooq.tables.MemberRoles;
import de.kittybot.kittybot.jooq.tables.Members;
import de.kittybot.kittybot.jooq.tables.Notifications;
import de.kittybot.kittybot.jooq.tables.ReactiveMessages;
import de.kittybot.kittybot.jooq.tables.Requests;
import de.kittybot.kittybot.jooq.tables.SelfAssignableRoleGroups;
import de.kittybot.kittybot.jooq.tables.SelfAssignableRoles;
import de.kittybot.kittybot.jooq.tables.Sessions;
import de.kittybot.kittybot.jooq.tables.SnipeDisabledChannels;
import de.kittybot.kittybot.jooq.tables.StreamUserEvents;
import de.kittybot.kittybot.jooq.tables.StreamUsers;
import de.kittybot.kittybot.jooq.tables.UserStatistics;
import de.kittybot.kittybot.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bot_disabled_channels</code>.
     */
    public static final BotDisabledChannels BOT_DISABLED_CHANNELS = BotDisabledChannels.BOT_DISABLED_CHANNELS;

    /**
     * The table <code>public.bot_ignored_members</code>.
     */
    public static final BotIgnoredMembers BOT_IGNORED_MEMBERS = BotIgnoredMembers.BOT_IGNORED_MEMBERS;

    /**
     * The table <code>public.guild_invite_roles</code>.
     */
    public static final GuildInviteRoles GUILD_INVITE_ROLES = GuildInviteRoles.GUILD_INVITE_ROLES;

    /**
     * The table <code>public.guild_invites</code>.
     */
    public static final GuildInvites GUILD_INVITES = GuildInvites.GUILD_INVITES;

    /**
     * The table <code>public.guild_tags</code>.
     */
    public static final GuildTags GUILD_TAGS = GuildTags.GUILD_TAGS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.member_roles</code>.
     */
    public static final MemberRoles MEMBER_ROLES = MemberRoles.MEMBER_ROLES;

    /**
     * The table <code>public.members</code>.
     */
    public static final Members MEMBERS = Members.MEMBERS;

    /**
     * The table <code>public.notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>public.reactive_messages</code>.
     */
    public static final ReactiveMessages REACTIVE_MESSAGES = ReactiveMessages.REACTIVE_MESSAGES;

    /**
     * The table <code>public.requests</code>.
     */
    public static final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.self_assignable_role_groups</code>.
     */
    public static final SelfAssignableRoleGroups SELF_ASSIGNABLE_ROLE_GROUPS = SelfAssignableRoleGroups.SELF_ASSIGNABLE_ROLE_GROUPS;

    /**
     * The table <code>public.self_assignable_roles</code>.
     */
    public static final SelfAssignableRoles SELF_ASSIGNABLE_ROLES = SelfAssignableRoles.SELF_ASSIGNABLE_ROLES;

    /**
     * The table <code>public.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.snipe_disabled_channels</code>.
     */
    public static final SnipeDisabledChannels SNIPE_DISABLED_CHANNELS = SnipeDisabledChannels.SNIPE_DISABLED_CHANNELS;

    /**
     * The table <code>public.stream_user_events</code>.
     */
    public static final StreamUserEvents STREAM_USER_EVENTS = StreamUserEvents.STREAM_USER_EVENTS;

    /**
     * The table <code>public.stream_users</code>.
     */
    public static final StreamUsers STREAM_USERS = StreamUsers.STREAM_USERS;

    /**
     * The table <code>public.user_statistics</code>.
     */
    public static final UserStatistics USER_STATISTICS = UserStatistics.USER_STATISTICS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
